"""R:R Distribution Audit -- pure, descriptive analysis functions over
already-computed, already-decided trades (each a plain dict with at least
`hit` and `r_multiple`, and for the independent R validation also
`direction`, `entry`, `stop_loss`, `take_profit_1`, `take_profit_2`).

Nothing here feeds back into any Strategy/Weight/Filter/Threshold/Entry/
TP/SL decision -- this module only describes trades BacktestEngine has
already resolved (see scripts/rr_distribution_audit.py, which is the only
caller that touches real backtest data). No trade is re-simulated, and no
decision logic from core/ or backtesting/ is imported or exercised here.
"""
from __future__ import annotations

import math
from statistics import mean, median

RR_BINS = [
    ("1.5-2R", 1.5, 2.0),
    ("2-3R", 2.0, 3.0),
    ("3-4R", 3.0, 4.0),
    ("4-5R", 4.0, 5.0),
    ("5-10R", 5.0, 10.0),
    ("10-20R", 10.0, 20.0),
    ("20-50R", 20.0, 50.0),
    ("50R+", 50.0, math.inf),
]
BELOW_FLOOR_LABEL = "below_1.5R"
GROSS_SHARE_THRESHOLDS = [5.0, 10.0, 20.0, 50.0]
CONCENTRATION_TOP_FRACTIONS = [0.001, 0.005, 0.01, 0.02, 0.05, 0.10]
TRIM_FRACTIONS = [0.001, 0.005, 0.01, 0.02, 0.05]


def classify_rr_bin(r: float) -> str:
    """Classifies a WINNING trade's realized R into one of RR_BINS, or
    BELOW_FLOOR_LABEL for a win whose realized R sits under the production
    min-R:R floor (1.5) -- never assumed empty, always computed from the
    real data actually passed in."""
    if r < 1.5:
        return BELOW_FLOOR_LABEL
    for label, lo, hi in RR_BINS:
        if lo <= r < hi:
            return label
    return "50R+"


def percentile(values: list[float], p: float) -> float | None:
    """Nearest-rank percentile -- the same method already used by
    optimization/extended_metrics.py's _percentiles, kept consistent
    across the project rather than reinvented differently here."""
    if not values:
        return None
    s = sorted(values)
    idx = min(len(s) - 1, max(0, round(p / 100 * (len(s) - 1))))
    return s[idx]


def is_win(trade: dict) -> bool:
    return trade["hit"] in ("TP1", "TP2")


def is_loss(trade: dict) -> bool:
    return trade["hit"] == "SL"


def is_unresolved(trade: dict) -> bool:
    return trade["hit"] == "NONE"


def winning_r_values(trades: list[dict]) -> list[float]:
    return [t["r_multiple"] for t in trades if is_win(t)]


def bin_distribution(trades: list[dict]) -> dict[str, dict]:
    """Item 4: R:R distribution of WINNING trades, plus explicit,
    never-silently-discarded accounting for winners below the 1.5R floor,
    losses, and unresolved (NONE) trades."""
    wins = [t for t in trades if is_win(t)]
    losses = [t for t in trades if is_loss(t)]
    unresolved = [t for t in trades if is_unresolved(t)]
    total_wins = len(wins)
    gross_win = sum(t["r_multiple"] for t in wins)

    labels = [BELOW_FLOOR_LABEL] + [b[0] for b in RR_BINS]
    buckets: dict[str, list[float]] = {label: [] for label in labels}
    for t in wins:
        buckets[classify_rr_bin(t["r_multiple"])].append(t["r_multiple"])

    result: dict[str, dict] = {}
    for label in labels:
        vals = buckets[label]
        bin_total_r = sum(vals)
        result[label] = {
            "trade_count": len(vals),
            "pct_of_winning_trades": (len(vals) / total_wins) if total_wins else 0.0,
            "total_realized_r": bin_total_r,
            "pct_of_gross_winning_r": (bin_total_r / gross_win) if gross_win else 0.0,
            "mean_realized_r": mean(vals) if vals else None,
            "median_realized_r": median(vals) if vals else None,
        }

    result["losses_SL"] = {
        "trade_count": len(losses), "total_realized_r": sum(t["r_multiple"] for t in losses),
    }
    result["unresolved_NONE"] = {
        "trade_count": len(unresolved), "total_realized_r": sum(t["r_multiple"] for t in unresolved),
    }
    return result


def gross_share_above_thresholds(trades: list[dict], thresholds: list[float] = GROSS_SHARE_THRESHOLDS) -> dict[str, dict]:
    """Item 5: share of gross winning R generated by winners strictly
    above each threshold (>5R, >10R, >20R, >50R)."""
    wins = [t for t in trades if is_win(t)]
    gross_win = sum(t["r_multiple"] for t in wins)
    result = {}
    for threshold in thresholds:
        above = [t["r_multiple"] for t in wins if t["r_multiple"] > threshold]
        total = sum(above)
        result[f">{threshold:g}R"] = {
            "trade_count": len(above),
            "total_realized_r": total,
            "pct_of_gross_winning_r": (total / gross_win) if gross_win else 0.0,
        }
    return result


def global_distribution_summary(trades: list[dict]) -> dict:
    """Item 5: the full global-distribution statistic set."""
    wins = [t for t in trades if is_win(t)]
    losses = [t for t in trades if is_loss(t)]
    unresolved = [t for t in trades if is_unresolved(t)]
    win_r = [t["r_multiple"] for t in wins]
    loss_r = [t["r_multiple"] for t in losses]

    gross_win = sum(win_r)
    gross_loss = abs(sum(loss_r))
    net_r = gross_win - gross_loss
    profit_factor = (gross_win / gross_loss) if gross_loss else (math.inf if gross_win > 0 else 0.0)
    resolved_count = len(wins) + len(losses)

    return {
        "total_trades": len(trades), "winning_trades": len(wins), "losing_trades": len(losses),
        "unresolved_trades": len(unresolved), "resolved_trades": resolved_count,
        "win_rate": (len(wins) / resolved_count) if resolved_count else 0.0,
        "gross_winning_r": gross_win, "gross_losing_r": gross_loss, "net_r": net_r,
        "profit_factor": profit_factor, "expectancy": (net_r / resolved_count) if resolved_count else 0.0,
        "mean_winning_r": mean(win_r) if win_r else None, "median_winning_r": median(win_r) if win_r else None,
        "p75_winning_r": percentile(win_r, 75), "p90_winning_r": percentile(win_r, 90),
        "p95_winning_r": percentile(win_r, 95), "p99_winning_r": percentile(win_r, 99),
        "max_winning_r": max(win_r) if win_r else None,
        "gross_share_above_thresholds": gross_share_above_thresholds(trades),
    }


def profit_concentration(trades: list[dict], top_fractions: list[float] = CONCENTRATION_TOP_FRACTIONS) -> dict[str, dict]:
    """Item 6: sorted winners descending by realized R; how much of gross
    winning R comes from the top N% of winning trades BY COUNT."""
    wins_sorted = sorted((t["r_multiple"] for t in trades if is_win(t)), reverse=True)
    gross_win = sum(wins_sorted)
    n = len(wins_sorted)
    result = {}
    for frac in top_fractions:
        top_n = max(1, round(frac * n)) if n else 0
        top_r = sum(wins_sorted[:top_n])
        result[f"top_{frac * 100:g}pct"] = {
            "n_trades": top_n, "total_realized_r": top_r,
            "pct_of_gross_winning_r": (top_r / gross_win) if gross_win else 0.0,
        }
    return result


def trim_analysis(trades: list[dict], trim_fractions: list[float] = TRIM_FRACTIONS) -> dict[str, dict]:
    """Item 6: POST-TRADE, analytical-only trim -- removes the top N%
    highest-realized-R WINNING trades (by count) and recomputes summary
    metrics over the remaining population. Never re-runs the strategy,
    never alters trade generation; a pure arithmetic exclusion over
    already-decided trades."""
    wins_sorted = sorted((t for t in trades if is_win(t)), key=lambda t: t["r_multiple"], reverse=True)
    losses = [t for t in trades if is_loss(t)]
    unresolved = [t for t in trades if is_unresolved(t)]
    gross_loss = abs(sum(t["r_multiple"] for t in losses))
    n_wins = len(wins_sorted)

    result = {}
    for frac in trim_fractions:
        trim_n = max(1, round(frac * n_wins)) if n_wins else 0
        remaining_wins = wins_sorted[trim_n:]
        gross_win = sum(t["r_multiple"] for t in remaining_wins)
        net_r = gross_win - gross_loss
        resolved_count = len(remaining_wins) + len(losses)
        trade_count = resolved_count + len(unresolved)
        profit_factor = (gross_win / gross_loss) if gross_loss else (math.inf if gross_win > 0 else 0.0)
        result[f"trim_{frac * 100:g}pct"] = {
            "n_trades_removed": trim_n,
            "trade_count": trade_count, "wins": len(remaining_wins), "losses": len(losses),
            "win_rate": (len(remaining_wins) / resolved_count) if resolved_count else 0.0,
            "gross_winning_r": gross_win, "gross_losing_r": gross_loss, "net_r": net_r,
            "profit_factor": profit_factor, "expectancy": (net_r / resolved_count) if resolved_count else 0.0,
        }
    return result


def independent_r_multiple(direction: str, entry: float, stop_loss: float, exit_price: float) -> float | None:
    """Item 9's exact, independently-coded validation formula --
    deliberately NOT calling SelectedSetup.risk_reward_tp1/tp2 (that would
    just compare the stored value against itself). Returns None if the SL
    distance is exactly zero (undefined R, reported as its own condition,
    never silently coerced to 0 or inf)."""
    risk = abs(entry - stop_loss)
    if risk == 0:
        return None
    if direction == "BUY":
        return (exit_price - entry) / risk
    return (entry - exit_price) / risk
